export {default as MyGamesComponent     } from './my-games';
export {default as LoginComponent       } from './login';
export {default as RegisterComponent    } from './register';
export {default as VerifyCode           } from './verify-code';
export {default as MyProfileComponent   } from './my-profile';
export {default as SearchComponent      } from './search';
export {default as GameDetailComponent  } from './game-detail';
export {default as CommentGameComponent } from './comment-game';
export {default as UserInfoVerifier     } from './user-info-verifier';